### ISSUE TITLE
Terminate is the only way to exit?

### ISSUE THREAD

**Issue by FreeMasen** [Boscop/web-view#105]
It does not appear the it would be possible to signal the event loop to exit gracefully. The note on `terminate` says that it exits without dropping. Does that mean the `WebView` is leaked? Is there a better method for exiting from inside the `invoke_handler`?

**Comment by zxey** [comment]
There are two function from underlying c code `terminate` and `exit`. It is confusing what each of them does and it also differs from platform to platform. We should probably unify them and provide one method on webview to gracefully exit the application.

More platform explanation if you want to look into this:
**Windows** (webview_mshtml.c):
- webview_terminate
  Invokes PostQuitMessage which queues WM_QUIT message to wndproc, which is not handled anyway
- webview_exit
  Destroys window, sending WM_DESTROY message to wndproc, which is correctly handled

  The correct one here to use is probably webview_exit

**Windows** (webview_edge.cpp):
- webview_terminate
  Invokes PostQuitMessage which gets correctly handled in wndproc (called browser_window::loop here)
 - webview_exit
  Invokes webview_terminate, so there is no difference

   The correct procedure to use here is to copy the logic from mshtml backend, use DestroyWindow and handle WM_DESTROY.

**Linux** (webview_gtk.c):
- webview_terminate
  Sets flag that main loop should exit
- webview_exit
  Does nothing

  webview_exit just needs to be removed

**macOS** (webview_cocoa.c):
- webview_terminate
  Sets flag that main loop should exit
- webview_exit
  Sends terminate message to application which in turn invokes webview_window_will_close which in turn invokes webview_terminate

  These should just be unified somehow so user can call webview_exit only (I think).

Hopefully this is good enough overview what happens underneath. On the rust side we need to introduce quit() method and on the c/c++/objc side we need to unify functions so they gracefully quit the application.

**Comment by carbotaniuman** [comment]
Can we just remove webview_terminate and make webview_exit clean everything up?

**Comment by FreeMasen** [comment]
@zxey Thanks for the detailed response! I am mostly thought #107 (though I want to double check that the gtk update is working). 

@carbotaniuman That is how I read @zxey's response, I was planning on removing `webview_terminate` from webview.h and the extern block of webview-sys. 

I am thinking it might make sense to add a `#[deprecated(note = "Please use exit instead")]` annotation on terminate in the rust project (though it could just be removed entirely).

**Comment by nothingismagick** [comment]
I totally agree with @zxey, but would caution against just removing an interface that has been there for a long time, no matter how confusing or semantically dualistic. A breaking change is a breaking change. That's why I really appreciate @FreeMasen 's thought to at least consider downstream consumers with the deprecation notice.

**Comment by zxey** [comment]
Yeah, the deprecation notice is definitely wanted, no need to create unnecessary breakage. I will probably release 0.6 after your PR gets merged, keep the deprecation during 0.6 and remove the method in 0.7.
