### ISSUE TITLE
Created window runs MSHTML7 compatibility mode

### ISSUE THREAD

**Issue by EclipseOnFire** [Boscop/web-view#106]
Hi,

I'm creating a new window and loading a simple HTML page but it seems to run MSHTML7 in compatibility mode instead of running its version 11.

Here's the popup provided by `alert(navigator.userAgent)`:
![image](https://user-images.githubusercontent.com/10947074/71212773-5099c800-22b2-11ea-97d5-7ff1c491c491.png)

I tried to investigate a little bit and found that the registry key needed to run the application without the compatibility mode was in:
```
HKEY_CURRENT_USER\潓瑦慷敲䵜捩潲潳瑦䥜瑮牥敮⁴硅汰牯牥䵜楡屮敆瑡牵䍥湯牴汯䙜䅅啔䕒䉟佒南剅䕟啍䅌䥔乏
```
Instead of:
```
HKEY_CURRENT_USER\SOFTWARE\Microsoft\Internet Explorer\MAIN\FeatureControl\FEATURE_BROWSER_EMULATION
```

Adding `<meta http-equiv="X-UA-Compatible" content="IE=edge" />` seems to have no effect.  
The workaround I found was to create the registry key manually (or programmatically, using a custom code).

Apparently [this registry key is being set by the webview library](https://github.com/zserge/webview/blob/1a9ebffc260142416d4dbfc24db48bc445317b26/webview.h#L1233). I suspect the bug is a linking error from the Rust compiler or an encoding issue. I don't really know why this is happening...

- System: Windows 10 64bits
- Toolchain: `stable-x86_64-pc-windows-gnu`
- GCC: `8.1.0`

Thanks.

**Comment by zxey** [comment]
Try to use this snippet and see if it helps:
```
<!doctype html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="UTF-8">
</head>
<body>
    <!--[if lt IE 11]>
    <div class="ie-upgrade-container">
        <p class="ie-upgrade-message">Please, upgrade Internet Explorer to continue using this software.</p>
        <a class="ie-upgrade-link" target="_blank" href="https://www.microsoft.com/en-us/download/internet-explorer.aspx">Upgrade</a>
    </div>
    <![endif]-->
</body>
</html>
```

**Comment by EclipseOnFire** [comment]
Oh sorry, I removed the `content` attribute from the code since I tried Edge and IE 9, 10, 11 before. I've got the same behavior with your template.

Even if it works, the registry key that was created is still encoded with chinese characters, which is wrong and may pollute the user's registry.
