### ISSUE TITLE
[Bug] Cmd line opens when running a production built application in windows. 

### ISSUE THREAD

**Issue by tensor-programming** [Boscop/web-view#111]
Windows 10
Webview version `0.5.4` with and without edge.

Been seeing this behavior in Tauri as well as WebView.  

Here is a screenshot of the behavior using only `webview` on windows 10: 
![win-bug-release](https://user-images.githubusercontent.com/22513880/71342601-3ae30780-252b-11ea-808d-42f75b936fc5.png)

This is a production built Exe using `cargo build --release` and when you run the executable, a command line opens up with it.  This seems to be the case for both Edge and MSHTML.  Removing any kind of I/O print statement does not resolve the problem either.

**Comment by zxey** [comment]
This is not a bug, Windows by default creates window and a console, if you don't want to create console, you need to put `#![windows_subsystem = "windows"]` at the top of main.rs, see `minimal.rs` example.

**Comment by tensor-programming** [comment]
Yeah, my bad.  Didn't know that was a thing in rust 1.18, some of the tauri devs also pointed this out.  Thank you.

**Comment by zxey** [comment]
No worries. :)
