### ISSUE TITLE
How to call async rust code from js

### ISSUE THREAD

**Issue by ThinkontrolSY** [Boscop/web-view#128]
I have some very time-consuming tasks in rust, if I use `invoke_handler` and call then from js, my UI stucked. 
Is there any way to call async rust code from js, or can invoke_handler except Future?

**Comment by sopium** [comment]
You can spawn a new thread (or maybe a tokio task, or send the task payload via a queue to a worker pool) from the invoke handler. Pass to the new thread a [`Handle`](https://docs.rs/web-view/0.6.0/web_view/struct.Handle.html). When the work is done, pass the result back to js via [`dispatch`](https://docs.rs/web-view/0.6.0/web_view/struct.Handle.html#method.dispatch) and [`eval`](https://docs.rs/web-view/0.6.0/web_view/struct.WebView.html#method.eval).

**Comment by ThinkontrolSY** [comment]
@sopium 
Thanks a lot
I am a very starter on rust, could you please post some example code about this ?

**Comment by sopium** [comment]
See the `timer` example. It's not exactly what you asked for but it demonstrates how to communicate with JS from another thread.

**Comment by ThinkontrolSY** [comment]
@sopium 
I see, it helps a lot, thanks

**Comment by zxey** [comment]
Closing the issue, some async processing can be seen in examples. If you need to clarify something, feel free to reopen this.
