### ISSUE TITLE
Sharing Example Code

### ISSUE THREAD

**Issue by tataDan** [Boscop/web-view#131]
I have a very simple example application that illustrates how it is possible to use web-view to get data from the user interface, process that data in Rust, and then insert the result of that processing into the user interface. Are there any suggestions as to how example code could be posted to either this web site or another web site?

**Comment by zxey** [comment]
Sure, I'd love some more examples people can learn from!

These are the steps you need to do:
- Create a 'fork' of this repository which will be your copy of this repository where you can do all your changes
- Clone your repository with `git`
- Add the example file with source code to `examples/` directory, say: `ui_data_processing.rs`
- Try if the example works with the command `cargo run --example ui_data_processing`
- Commit and push changes to your repository with `git`
- Create a Pull Request on this repository, which I can then approve and get the example here
    - You can find more info about Pull Requests [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork)

Don't hesitate to ask if something is not clear.

**Comment by tataDan** [comment]
I have created an example application that I had hoped could be placed in the examples directory. However, when I was testing it in my clone of my fork, I discovered that it needs two crates that are not available in the examples directory.  These crates are grep = "0.2.4" and walkdir = "2.3.1", both of which are in crates.io.

Is there a way I could somehow make this application available?

**Comment by zxey** [comment]
Yes, just place the `grep = "0.2.4"` and `walkdir = "2.3.1"` into the `[dev-dependencies]` section web-view's Cargo.toml file.

**Comment by tataDan** [comment]
Okay, I can do that for the Cargo.toml file in my fork, but how will visitors to web-view know that the example application exists in my fork?  There are currently 72 forks and it is unlikely that a visitor would know that it there.

**Comment by zxey** [comment]
If it is something that shows something new that is not already covered by examples, you can create Pull Request and I can merge it here.

**Comment by zxey** [comment]
Examples were merged some time ago, closing.
