### ISSUE TITLE
Running a react.js app only shows a blank window

### ISSUE THREAD

**Issue by Ante-dev** [Boscop/web-view#140]
When I try opening the index.html file from a built react.js app the web-view only shows a blank window. Opening it in Firefox on the other hand works like expected.
How can I run react.js app from the web-view?

**Comment by sopium** [comment]
Are you using IE, i.e., you are on Windows and are not using the edge feature? Does it work in the standalone IE?

**Comment by Ante-dev** [comment]
Thank you for your reply.
I'm using Linux. So Webkitgtk gets launched, when running Web-View.

**Comment by sopium** [comment]
How do you build and use the html?

If you use `Content::Html(include_str!("index.html"))`, note that it's different from using a file URL in firefox, because the web-view won't be able to find other resources in the file system. Try to use [inline-assets](https://www.npmjs.com/package/inline-assets) to inline all your assets (css, js, html) into one `index.html`. Alternatively, use `rust-embed` and a true web server, like the `actix` or `todo-yew` examples.

**Comment by nothingismagick** [comment]
The problem likely has to do with dynamic imports. You could also check out
tauri (which uses this library under the hood). We have an example that
uses react create app, and take care of all the inlining for you.

>
https://github.com/tauri-apps/tauri

**Comment by xasopheno** [comment]
I'm also having a problem with a react app. I'm serving from an actix server. While this is running locally, I can hit it from my browser and it works as expected, but the web-view shows a blank page. It seems like background color from the css is loading, but nothing else. Is there something I'm missing here? 
```
#[actix_rt::main]
async fn main() -> Result<(), actix_web::Error> {
    std::env::set_var("RUST_LOG", "socool_server=info, actix_web=info");
    env_logger::init();

    let port = env::var("PORT")
        .unwrap_or_else(|_| "4599".to_string())
        .parse()
        .expect("PORT must be a number");
    println!("Listening on {}", &port);

    let (server_tx, server_rx) = mpsc::channel();

    thread::spawn(move || {
        let sys = actix_rt::System::new("server");
        let server = HttpServer::new(|| {
            App::new()
                .wrap(Cors::new().finish())
                .service(
                    web::scope("/api")
                        .route("/render", web::post().to(render))
                        .route("/songs/{filename:.*}", web::get().to(get_file)),
                )
                .route("/compose", web::get().to(single_page_app))
                .route("/play/{filename:.*}", web::get().to(single_page_app))
                .default_service(Files::new("/", "./src/server/build").index_file("index.html"))
        })
        .bind(("0.0.0.0", port))
        .unwrap();

        let port = server.addrs().first().unwrap().port();
        let server = server.run();

        let _ = server_tx.send(server);

        let _ = sys.run();
    });

    let server = server_rx.recv().unwrap();

    web_view::builder()
        .title("app")
        .content(Content::Url("http://localhost:4599/compose"))
        .size(800, 600)
        .resizable(true)
        .debug(true)
        .user_data(())
        .invoke_handler(|_webview, _arg| Ok(()))
        .run()
        .unwrap();

    // gracefully shutdown actix web server
    let _ = server.stop(true).await;
    Ok(())
}
```

<img width="889" alt="Screen Shot 2020-03-23 at 2 01 13 AM" src="https://user-images.githubusercontent.com/7309943/77286708-348b3580-6caa-11ea-9aa6-ad44c84e3b95.png">

**Comment by marcushill** [comment]
A bit late, but I had the same problem with a react app even when using `inline-assets` and switching react-router to use `HashRouter` instead of `HistoryRouter` seems to have solved the problem. I was getting something like "SecurityError: Operation is insecure" in the webview console.

**Comment by Ante-dev** [comment]
I finally got it working to load a built react.js app into web-view. 
This time I loaded the html file with the following method into the web-view.

`Content::Url("file:///path/to/index.html")`
instead of
~~`Content::Html(include_str!("index.html"))`~~

This is actually the same way as firefox would handle the html file.
