### ISSUE TITLE
Running a vue.js app error on windows

### ISSUE THREAD

**Issue by betta-cyber** [Boscop/web-view#145]
When I try opening the index.html file from a built vue.js app the web-view shows scripts error. does web-view not support vue.js or other reason?  my ie's version is ie11.

and i still find a error is that i use `cargo run --` my web-view app works. but i try to build a release and run it. I got an error 
```
➜  gs git:(master) ✗ target/release/gs.exe
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Initialization', src\main.rs:37:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

how to fix it ?

**Comment by betta-cyber** [comment]
ok, i find my first question, it's my code's error. I should use es5 syntax not es6.

**Comment by zxey** [comment]
Yes, it's because on Windows we use IE11, it probably does not support the new syntax.
