### ISSUE TITLE
React Webpack

### ISSUE THREAD

**Issue by xasopheno** [Boscop/web-view#156]
I'm having trouble serving a react webpack build. I'm serving from an actix server. While this is running, I can hit it from my browser and it works as expected, but the web-view shows a blank page. It seems like background color from the css is loading, but nothing else. Is there something I'm missing here? I'm really excited about this as a light weight container for a react-based ui if I can get it working. Running OSX.

```
fn main() -> Result<(), actix_web::Error> {
    std::env::set_var("RUST_LOG", "socool_server=info, actix_web=info");
    env_logger::init();

    let port = env::var("PORT")
        .unwrap_or_else(|_| "4599".to_string())
        .parse()
        .expect("PORT must be a number");
    println!("Listening on {}", &port);

    let (server_tx, server_rx) = mpsc::channel();

    thread::spawn(move || {
        let sys = actix_rt::System::new("server");
        let server = HttpServer::new(|| {
            App::new()
                .wrap(Cors::new().finish())
                .default_service(Files::new("/", "./src/server/build").index_file("index.html"))
        })
        .bind(("0.0.0.0", port))
        .unwrap();

        let port = server.addrs().first().unwrap().port();
        let server = server.run();

        let _ = server_tx.send(server);

        let _ = sys.run();
    });

    let server = server_rx.recv().unwrap();

    web_view::builder()
        .title("app")
        .content(Content::Url(format!("http://localhost:{}", port)))
        .size(800, 600)
        .resizable(true)
        .debug(true)
        .user_data(())
        .invoke_handler(|_webview, _arg| Ok(()))
        .run()
        .unwrap();

    // gracefully shutdown actix web server
    // let _ = server.stop(true).await;
    Ok(())
}
```

<img width="889" alt="Screen Shot 2020-03-23 at 2 01 13 AM" src="https://user-images.githubusercontent.com/7309943/77286708-348b3580-6caa-11ea-9aa6-ad44c84e3b95.png">

**Comment by zxey** [comment]
The first thing that comes to mind is that you are using async, and then blocking the main thread with webview::run(). Try running actix only in its designated thread without using `#[actix_rt::main]`.

**Comment by xasopheno** [comment]
@zxey thanks for taking a look at this with me. I made the changes you request and updated the code above, but no luck. Same result.

**Comment by edko99** [comment]
If you right-click on the web-view, you will get a menu with the "inspect element" option and you can inspect just like in Safari. I think this menu is enabled by using `debug(true)` in the builder (which I see you do).

**Comment by xasopheno** [comment]
thanks @edko99 that's great! Found I had tried to start an audioCtx which doesn't exist. Works great. Thanks for the help. Glad I can now debug.
