### ISSUE TITLE
Different (native?) dropdown "select" tags

### ISSUE THREAD

**Issue by MGlolenstine** [Boscop/web-view#157]
I'm trying to write an application that would work with the option to "select" via the dropdown.
On Linux, the `option` theme is overridden by the system's theme.

This is how it looks in the HTML-Viewer and browser
![image](https://user-images.githubusercontent.com/9406770/77336694-309df880-6d28-11ea-9383-71639623ce7a.png)
and this is how it looks in the app
![image](https://user-images.githubusercontent.com/9406770/77336738-3dbae780-6d28-11ea-9a47-cb605154401e.png)
Is there a way to prevent the GTK theme from overriding the `select` dropdowns?
code:

```HTML
<select name="instance" id="instance" class="form-control" style="width: 100%;">
    <option value="36565">Port 36565</option>
</select>
```

**Comment by zxey** [comment]
Well you can either use the default style for `select` and `option` and all other widgets so it is consistent or you can provide custom implemented select with option, I believe some css frameworks do this. I do not think you can override `option`'s default style. I agree it is not optimal, but web-view just provides bindings to native webviews, it does not do any styling.
