### ISSUE TITLE
Pass data from JS to Rust

### ISSUE THREAD

**Issue by MGlolenstine** [Boscop/web-view#158]
I'm using some `input`s on my "website" and I'm trying to get the data back to Rust, but I don't see how.

1. `invoke_handler` only has one argument and that argument is the name of a snippet it should execute, I don't see a way to send data over that. 
```
.invoke_handler(|webview, arg| {
```
2. If trying to fetch data via Rust, using `eval` function, there's nothing returned in the `Result`'s `Ok`
```
webview.eval("document.querySelector(\"#lease_time\")").ok();
```
3. I also tried using the `user_data`, but I don't know how to access it in JS.
I do know that I can access [it in Rust](https://github.com/Boscop/web-view/blob/master/examples/timer.rs#L49), but I don't know how to access it in JS

**Comment by green-s** [comment]
The function you give to `invoke_handler` is a callback. Its second argument (`arg`) is a message from JS, not a name. You send a message from JS by calling `external.invoke(message)`.

**Comment by MGlolenstine** [comment]
Yes, I understood that.
I meant `message`'s name, but I see what you mean.
I'm still wondering how I'd get a second or a third parameter to transfer data.

**Comment by evilches-cj** [comment]
The data you pass back is a string. You can send JSON back and parse it with serve, for example.

**Comment by MGlolenstine** [comment]
Oh, that makes sense. Sending JSON as an object.

Thanks!
