### ISSUE TITLE
Webview not playing videos

### ISSUE THREAD

**Issue by hyousef-rusty** [Boscop/web-view#170]
I've the below that worked correctly in the browser, but it gives `Invalid Source` at webview:
```html5
<!doctype html>
<html>
    <body>
        <button onclick="external.invoke('open')">Run</button>
        <button onclick="external.invoke('close')">Close</button><br>
        <br>
        <video width="320" height="240" controls>
            <source src="c:/photos/file.webm" type="video/webm">
            // <source src="file.webm" type="video/webm">
        </video>
    </body>
</html>
```

![image](https://user-images.githubusercontent.com/60115476/80286660-53f80100-8735-11ea-8675-db6bb8b5e871.png)

**Comment by edko99** [comment]
If you are running this in the IE version of the plugin, you may need to specify the `codecs` attribute. Please check: https://stackoverflow.com/questions/21124885/html5-video-not-working-in-ie-11

**Comment by hyousef-rusty** [comment]
Actually I'm running it using:
```toml
web-view = "0.6.2"
```

Which means I'm not using `Edge`, once I tried to use `Edge` situation became worst as `img` tag stopped working as well.

Even though I tried using the codecs but nothing changed:
```html5
<source src="file.webm" type="video/webm; codecs='vp8.0, vorbis'">
```

**Comment by hyousef-rusty** [comment]
Today I tried `mp4` format as below, which is fine in the browser, regardless run from file or from server, but still having the same issue with `web-view` :(  :

```html5
        <video width="320" height="240" preload="none" loop controls autoplay muted id="vid">
            <source src="output.mp4" type="video/mp4">
        </video>
```

**Comment by edko99** [comment]
I am using 0.5.8 in my project, and Edge works pretty well. Sure, there are things that don't work with that version of Edge (like shadow DOM), which will surely work when the library supports the Chrome-backed version, but I am surprised about `img`s not working.

**Comment by hyousef-rusty** [comment]
I got this once tried working with "0.5.8"

**Comment by zxey** [comment]
The build failing is not accurate, we no longer use travis, need to switch it for Github Action build banner.

**Comment by hyousef-rusty** [comment]
I liked to share this with you, may be I'm the one who is doing some mistake in calling the image, as see below, if I called an image from url, it is displayed correctly, if I call it from file, though I tried to put the file in 3 different locations (in src, in cargo root, and beside the .exe) but none of them worked!


![image](https://user-images.githubusercontent.com/60115476/80522064-9f5c1a80-8994-11ea-97e2-e78414ee731b.png)

**Comment by edko99** [comment]
The problem is that the web view cannot resolve the `src="lamp.jpg"`. The only way it can communicate with the Rust back end is either by calling the `extern.invoke` function, or if your application is listening on a localhost http connection (although Windows has some limitations on this). Something you can do to avoid asking your Rust backend for the image data is to convert your image to a data URL (https://stackoverflow.com/questions/8499633/how-to-display-base64-images-in-html)

**Comment by hyousef-rusty** [comment]
I tried it with [rocket](https://rocket.rs/) but still getting same result

![image](https://user-images.githubusercontent.com/60115476/80530676-07652d80-89a2-11ea-8f4c-bf1bb64dfc60.png)

I tried encoding the image, but did not work:

![image](https://user-images.githubusercontent.com/60115476/80531647-a2aad280-89a3-11ea-9b44-c1a9d32a379b.png)

**Comment by hyousef-rusty** [comment]
It is working now:
1. For the reading from file path: I wrote it before as `c:\\...` while it should be written as `c:/..`
2. For reading from the server, I rewrote the full path as `/static/lamp.jpg` instead of `lamp.jpg` only

![image](https://user-images.githubusercontent.com/60115476/80536261-c9203c00-89aa-11ea-8cad-f02c13036b38.png)
 

![image](https://user-images.githubusercontent.com/60115476/80536105-86f6fa80-89aa-11ea-9c4d-906928ecd360.png)

So, now back to our main point: `playing videos` :)

**Comment by hyousef-rusty** [comment]
So, now both image and video are working, but should be run/loaded from a server. Thanks for your support 👍 

![image](https://user-images.githubusercontent.com/60115476/80537409-b0b12100-89ac-11ea-8ac7-f826839fd9f9.png)
