### ISSUE TITLE
Getting key pressed to exit a loop

### ISSUE THREAD

**Issue by hyousef-rusty** [Boscop/web-view#173]
In `JavaScript` I can get keypressed as:
```javascript
document.addEventListener('keydown', function(event) {
    if (event.keyCode == 37) {
        alert('Left was pressed');

    }
    else if (event.keyCode == 39) {
        alert('Right was pressed');
    }
}, true);
```

In rust openCV, I can get keypressed as:
```rust
loop{
    let key = highgui::wait_key(10)?;
    if key > 0 && key != 255 {
          break;
    }
}
```
The rust code did not work with webview, how can I get key pressed to exit the loop?

**Comment by zxey** [comment]
You can read about this directly in the README of this project:
Rust:
```Rust
// ... Simplified for the sake of brevity.
web_view::builder()    
    .invoke_handler(|webview, arg| {
        match arg {
            "test_one" => {
                // Do something in Rust!
            }
            "test_two" => {
                // Invoke a JavaScript function!
                webview.eval(&format!("myFunction({}, {})", 123, 456))
            }
            _ => unimplemented!(),
        };
    })
```
JS:
```JavaScript
// Executes our "invoke_handler" - passing the value "test_one" as the second parameter.
external.invoke('test_one');

// Executes our "invoke_handler", which in turn calls "myFunction" below.
external.invoke('test_two');

function myFunction(paramOne, paramTwo) {
    console.log(paramOne);
    console.log(paramTwo);
}
```

It is the second paragraph here: https://github.com/Boscop/web-view

Basically the gist of communication from JS to Rust is that you need to serialize what you want to string and then call `external.invoke(yourDataSerializedToString)`.

In order to call JS from Rust you need to call `webview.eval(string_you_want_evaluated_in_javascript)`.

**Comment by hyousef-rusty** [comment]
I already read that part and tested it, but this is work with static input, that has a clear point at which I want to call the JavaScript function, but in my case once I want it with a dynamic `evenlistner` that is trigger based an input from the user by keyboard press, not by a static and well know/predetermined action within the rust code

**Comment by hyousef-rusty** [comment]
I also tried:
```rust
let x = wv.eval(&format!("myFunction({}, {})", 123, 456));
println!("x = {:#?}", x);
```
With
```JavaScript
        function myFunction(paramOne, paramTwo) {
            return (paramOne+paramTwo);
        }
```
But got the output as:
```bash
x = Ok(
    (),
)
```
And did not return a value to rust?

**Comment by MGlolenstine** [comment]
`eval` only returns `Ok(())` or `Error` to let you know if the evaluation you ran has been successful or not.
You can get data back from JS by executing `external.invoke("data to be passed in one string")` on the JS side.
That data will be returned within `invoke_handler` part of the `WebViewBuilder`. 

You can append `<id>: ` to the data that has been sent from JS to do a `match` on it within the `invoke_handler` and call a function that should be called according to your data.

If you want to get your data from the function above, you can do something like this:
```Rust
fn main() {
   let html = r#"<script>
        function myFunction(paramOne, paramTwo) {
            external.invoke(paramOne+paramTwo);
        }</script>"#;
    web_view::builder()
        .title("Minimal webview example")
        .content(Content::Html(html))
        .size(800, 600)
        .resizable(true)
        .debug(true)
        .user_data(())
        .invoke_handler(|_webview, _arg| {
            println!("Sum is {}", _arg);
        })
        .run()
        .unwrap();
}
```
and then if you call `wv.eval(&format!("myFunction({}, {})", 123, 456));`, the sum should be printed.
