### ISSUE TITLE
Debugging Edge web-view

### ISSUE THREAD

**Issue by edko99** [Boscop/web-view#174]
When running in debug mode in Safari, there is this very useful right-click option which can open the Inspect menu. Is there a way to enable a similar functionality on Windows, when running the Edge version of the web-view?

**Comment by edko99** [comment]
Sorry. This question has been asked before. The solution is to use the Edge Developer Tools app.

**Comment by brandonros** [comment]
How do you connect to the Edge Developer Tools?

**Comment by brandonros** [comment]
This one? https://www.microsoft.com/en-us/p/microsoft-edge-devtools-preview/9mzbfrmz0mnj#activetab=pivot:overviewtab? Not the one built into Edge like remote debugging/inspect?

**Comment by brandonros** [comment]
https://github.com/Boscop/web-view#installation-and-configuration Got it. Edge is not the default on Windows.
