### ISSUE TITLE
[Question] Is there a way to persist data like cookies, localstorage?

### ISSUE THREAD

**Issue by pjmp** [Boscop/web-view#184]
I'm trying to write a basic webview around a website that requires authentication via 3rd party sign-in method eg Google sign-in, Facebook etc.
I can login fine but the next time i run my app, I'm asked to login again because the session is not persistent, is it possible to persist session information (unless cleared)?

Thanks!

**Comment by zxey** [comment]
You can definitely save data, you have web apis and Rust at your disposal. You can query the cookies with javascript send them to Rust and then to disk, you can then load them the other way around. Look at Mozilla Developer Network for js cookie api documentation and use the Rust standard library for saving persistent data to file or you can look for a crate for that.
