### ISSUE TITLE
How can i open the webview but without the console window?

### ISSUE THREAD

**Issue by SamukaDEV** [Boscop/web-view#187]

**Comment by FrankenApps** [comment]
If you compile your program on windows, you can run the following command: `cargo rustc — release — -Clink-args= " SUBSYSTEM:WINDOWS /ENTRY:mainCRTStartup" ` 
For other operating system just search on how to hide the console window when running a rust program.

**Comment by tensor-programming** [comment]
You don't need to do all of that, you can just add this to the top of your `main.rs` file
```
  
#![cfg_attr(
  all(not(debug_assertions), target_os = "windows"),
  windows_subsystem = "windows"
)]
```

**Comment by zxey** [comment]
Closing as answered.

**Comment by SamukaDEV** [comment]
Thanks a lot, im new on Rust Programing! 
Nice 

\o/
