### ISSUE TITLE
Open Webview without console

### ISSUE THREAD

**Issue by SamukaDEV** [Boscop/web-view#188]
How can i open the webview but without the console window?
or something like that!

is it possible?

**Comment by nothingismagick** [comment]
hey - you might have a bit more success with https://tauri.studio - its based on this crate (for the time being) but goes further and solves a lot of the actual implementation issues surrounding apps built with WebView. check it out and join our discord if you need help. github issues are maybe not the best platform for this kind of question.

**Comment by FrankenApps** [comment]
See #187

**Comment by zxey** [comment]
Closing as duplicate, answered in #187.
