### ISSUE TITLE
Context menu / app menu?

### ISSUE THREAD

**Issue by fschutt** [Boscop/web-view#19]
Just a question, but is there any way to create an application menu or a right-click context menu using webview? Thanks.

**Comment by Laaas** [comment]
https://stackoverflow.com/questions/4909167/how-to-add-a-custom-right-click-menu-to-a-webpage#4909312

**Comment by fschutt** [comment]
No, I meant a "real" context menu, a native one. For example, a webpage-based context menu doesn't go beyond the boundaries of the parent window. Same with the app menu. Of course, you could re-build it yourself in HTML + JS, but (1) you would be limited to the rectangle of the app window and (2) it wouldn't feel "native" in any way.

I am not sure if the webview project (which this is based on) exposes something like this. For example, in Electron I can just set a menu from Javascript and it will create a "native" app menu for each platform. Same with the context menu.

**Comment by Boscop** [comment]
This would be useful but I'm not sure if IE's engine exposes this functionality in its API..

**Comment by quadrupleslap** [comment]
zserge/webview does not expose something like this, and neither does the UWP WebView or Apple's not-deprecated WKWebView, which zserge/webview uses (Apple's old APIs offered this, though.)
