### ISSUE TITLE
Should step be blocking?

### ISSUE THREAD

**Issue by bgaster** [Boscop/web-view#210]
Looking at the function:

```
pub fn step(&mut self) -> Option<WVResult> {
        unsafe {
            match webview_loop(self.inner.unwrap(), 1) {
                0 => {
                    let closure_result = &mut self.user_data_wrapper_mut().result;
                    match closure_result {
                        Ok(_) => Some(Ok(())),
                        e => Some(mem::replace(e, Ok(()))),
                    }
                }
                _ => None,
            }
        }
    }
```

Why is 1 (i.e. blocking) passed to webview_loop? I've found on Mac OS at least this can cause it to be unresonsive with respect to incoming data, i.e. no the same thread. Changing this to 0 gives the behavior I expected.

**Comment by helgoboss** [comment]
Similar issue here, on Windows (haven't tried on other OS so far). If the web view window is not in foreground, `step()` seems to block until the user brings it back to foreground. This is especially annoying when sending the web view an `exit()` task - which it can never receive unless the user clicks the window and thereby making the event loop continue.

**Comment by helgoboss** [comment]
Ah, I see this has been changed already in dbc1f7e68ab83fe75e3a73c4f21a57c31b8c2a51! It fixes my issue. Unfortunately this seems to be exactly the change which introduced high CPU usage reported in #241.

**Comment by zxey** [comment]
This changed back again, closing this for now.
