### ISSUE TITLE
Save cookies from 3rd party website

### ISSUE THREAD

**Issue by MGlolenstine** [Boscop/web-view#211]
I'm trying to make a wrapper for a 3rd party website to make it a desktop application.
On the website you do have to login with Google's Account, but I'm unsure on how to either
* Inject the JS code for communication
* Get cookie data into rust without JS injection

There's tons of examples, but none that would use JS injection or running and modifying HTML from a website we don't have control over.

I assume it would be possible to use `localStorage` as well, but I still don't know how, as I don't really have access to the JS part of the web app.

Any help would be much appreciated.

**Comment by MGlolenstine** [comment]
I figured out that I can capture everything I send using `webview.eval("external.invoke(document.cookie)")` and parse it further.

**Comment by DumbMahreeo** [comment]
Hi, I'm trying to achieve something similar, could you tell how you did?
Basically I don't understand how to inject JS code (since the website needs to actually call invoke_handler, right?)
