### ISSUE TITLE
Webview's future with winrt-rs

### ISSUE THREAD

**Issue by Blakeinstein** [Boscop/web-view#216]
I now see [winrt-rs](https://github.com/microsoft/winrt-rs) as a viable alternative to the current c calls.

I think it would be beneficial in improving code coverage and safety.

**Comment by zxey** [comment]
You are right, it definitely can be used for Edge bindings on Windows. I unfortunately do not have the time to fully delve into this, but would happily review any changes that would implement this or partially implement parts of this.

There is also https://github.com/sopium/webview2 which does not use winrt-rs directly, but uses the underlying com-rs library. We can potentially use it, use parts of it or contribute winrt-rs implementation there.

**Comment by Blakeinstein** [comment]
I would love to attempt but I am having difficulties understanding the import structure as I am very new to rust.
I was already looking into it and If I make progress I will let you know.
