### ISSUE TITLE
Question: Is it possible to update the HTML being displayed?

### ISSUE THREAD

**Issue by eedahl** [Boscop/web-view#22]
Please excuse me if it's faux pas to ask a question in issues.

The way I'm using web-view is reading a few files, building a html-table and feeding that to web-view with
```rust
    let size = (900, 778);
    let resizable = false;
    let debug = true;
    let init_cb = |_webview| {};
    let frontend_cb = |_webview: &mut _, _arg: &_, _userdata: &mut _| {};
    let userdata = ();
    run(
        "WR-stats",
        Content::Html(html),
        Some(size),
        resizable,
        debug,
        init_cb,
        frontend_cb,
        userdata,
    );
```
Eventually I want to listen for changes in a file, and if there are reread that file and rebuild the html. Is it possible to simply swap out the html being displayed with this new rebuilt html?

**Comment by Boscop** [comment]
You can use `eval` to set `document.documentElement.innerHTML` like described here:
https://github.com/zserge/webview/issues/79#issuecomment-359863543

**Comment by Boscop** [comment]
You call this eval function from your Rust host:
https://github.com/Boscop/web-view/blob/master/src/lib.rs#L144

**Comment by eedahl** [comment]
Yeah, but I need a `WebView` object to do that if I understand this correctly, which I don't get from calling `run` or seemingly anything else. I've now managed to call functions that call functions that access the `WebView` object, if a by rather circumvent methods. Trying to learn form your timer example I've arrived at sending
```rust
        move |webview| {
            webview.dispatch(|webview, userdata| {
//listener code that calls
//update_html(webview);
            })
        }
```
where `update_html` is
```rust
fn update_html<'a, T>(webview: &mut WebView<'a, T>) {
    let html_table = create_html_table();//
    let html = create_html(html_table);
    //r#"<!doctype html><html><body><h1>a horse is a horse is a horse</h1></body></html>"#;
    println!("blep");
    webview.eval(&format!(
        "{}{}{}",
        "document.documentElement.innerHTML=\"", html, "\""
    ));;
}
```
which works for the mock example (a horse is a horse is a horse) and should work in the more general example given that I find a replacement for Go's JSEscapeString.

**Comment by Boscop** [comment]
Yes, the init callback will give you the `WebView` object which you can call eval on (also later if you keep it around).
Not sure if there's a crate that does [what `JSEscapeString` does](https://github.com/gorilla/template/blob/master/v0/escape/funcs.go#L77-L133) but it's easy to do the same manually..
(A quick crates search only turned up [a crate](https://crates.io/crates/unescape) that does the opposite.)

**Comment by eedahl** [comment]
This solution serves the dual function of making ones' skin crawl while doing the trick for now, haha.
```rust
html = html.replace(r#"""#, r#"\""#).replace("/", r"\/").replace(r"'", r"\'").replace("\n", r"\n").replace("\r", r"\r");
```

**Comment by Boscop** [comment]
Yea, you can always optimize it later :)

**Comment by quadrupleslap** [comment]
@eedahl you can use web_view::escape to safely pass strings to JavaScript now, but it hasn't been published to crates.io.

**Comment by Boscop** [comment]
Thanks @quadrupleslap, I'll publish it to crates.io now :)

**Comment by Boscop** [comment]
It's on crates.io now, v0.2.1

**Comment by eedahl** [comment]
Wow, that's very cool, thanks for bothering with this! I'll leave it an exercise to myself to implement it too at some point, I confess it's not a hard problem but my Rust is bakery fresh.

**Comment by eedahl** [comment]
@quadrupleslap I think there's one last thing or so `web_view::escape` doesn't escape.
```rust
webview.eval(&format!(
        "document.documentElement.innerHTML=\"{}\";",
        html
    ));
works for me with my patented eye-bleed
```rust
    html = html.replace(r#"""#, r#"\""#).replace("/", r"\/").replace(r"'", r"\'").replace("\n", r"\n").replace("\r", r"\r");
```
but web_view escape gives a scripting error, "Expected ";""

**Comment by quadrupleslap** [comment]
`web_view::escape` adds its own quotes, but if that's not the problem, could you please send some erroring HTML so that I can try fixing it?

**Comment by eedahl** [comment]
That doesn't seem to be the issue, when I do
```
webview.eval(&format!(
        "document.documentElement.innerHTML={};",
        web_view::escape(&html)
    ));
```
(i.e., without quotes) it simply displays \n \n \n \n

This should do:
https://pastebin.com/wPVR4ER6
Please excuse the mess, it's generated.

**Comment by eedahl** [comment]
Know what, it might just be me doing threading incorrectly, because
```rust
        move |webview| {
            webview.dispatch(|webview, userdata| {
                let wr_tables = io::read_wr_tables();
                let targets_table = io::read_targets_table();

                if let Ok(pr_table) = io::read_state() {
                    println!("penic");
                    let data = io::populate_table_data(&pr_table, &wr_tables);
                    let html_table = html::create_html_table(&data, &targets_table);
                    let mut html = html::create_html(html_table);
                   update_html(webview, html.clone());
                }
            });
```
seems to work just fine, while
```rust
        move |webview| {
            std::thread::spawn(move || {
                //read wr_tables
                let wr_tables = io::read_wr_tables();

                //read targets_table
                let targets_table = io::read_targets_table();

                loop {
                    if let Ok(pr_table) = io::read_state() {
                        println!("penic");
                        let data = io::populate_table_data(&pr_table, &wr_tables);
                        let html_table = html::create_html_table(&data, &targets_table);
                        let mut html = html::create_html(html_table);
                        html = html.replace(r#"""#, r#"\""#)
                            .replace("/", r"\/")
                            .replace(r"'", r"\'")
                            .replace("\n", r"\n")
                            .replace("\r", r"\r");

                        webview.dispatch(|webview, userdata| {
                            update_html(webview, html.clone());
                        });
                    }
                    std::thread::sleep(std::time::Duration::from_secs(5));
                }
            });
        }
```
gives the four \n mentioned. Apologies.

**Comment by quadrupleslap** [comment]
Sorry, it only serializes strings, and only for JavaScript. I'll get on implementing that, though, it sounds a lot more useful. :P

**Comment by Boscop** [comment]
If the `escape` function used double quotes or no quotes, it would be able to be re-used inside the JSON escaping function, too, right?
If so, I think `escape` should strive to be compatible with that, so it can be re-used :)

**Comment by eedahl** [comment]
@quadrupleslap Just a heads-up that [unescape](https://github.com/saghm/unescape-rs/issues/1) would probably be up for a PR with escape functionality

**Comment by phase** [comment]
Using this
```rust
webview.eval(format!("document.documentElement.innerHTML=String.raw`{}`", YOUR_HTML).unwrap();
```
looks like it works fine, but I did notice that only the JS in my original HTML was being parsed for some reason. I'm not sure if that's a side effect of this or webkit.
