### ISSUE TITLE
[Question] How to resolve a failure to infer the types on a WebViewBuilder

### ISSUE THREAD

**Issue by AZMCode** [Boscop/web-view#221]
Even though the format

![Screenshot at 2020-08-29 19-18-54](https://user-images.githubusercontent.com/15837568/91648688-7332d200-ea38-11ea-88b3-214aa8f9e32e.png)
![Screenshot at 2020-08-29 19-20-00](https://user-images.githubusercontent.com/15837568/91648690-7463ff00-ea38-11ea-80ee-87d05102d6f4.png)
It seems the compiler is not able to determine the types needed for the builder to function. This is very odd since the coe shown above is formatted very similarly to the example code. Even the main change, (A non-anonymous invoke handler), is commented out. What could be the problem?

**Comment by bytebuddha** [comment]
I haven't used this library in a long time but I've used rust for a long time, and can help you with this error. When you look at the docs [here](https://docs.rs/web-view/0.6.3/web_view/fn.builder.html) You can see there are 1 lifetime and 3 type parameters. These can generally be inferred by the compiler **IF** you have passed the object they are constrained to. You can see in the docs that the 'I' param is equal to the type of the closure passed to invoke_handler, so if invoke_handler is not called it cannot infer the type of it and you get this error complaining about type inference. You can fix this by calling invoke_handler, or if you wish to keep it commented out you can tell the builder function the type like this.

**I Have not tested this code**
```
builder::<_, Fn(&mut WebView<T>, &str) -> WVResult, _, _>()
     // call builder methods here
```

One thing to notice is the underscore's. If the compiler can figure out what those types are supposed to be you don't have specify them and you can use the underscore to just use whatever the compiler thinks they should be(If it can figure them out). Here is the section of the [rust book](https://doc.rust-lang.org/stable/rust-by-example/generics/gen_fn.html) that talks about generic functions, there are some good examples in there.

PS. The weird `::<_>` syntax is called turbofish syntax here's the related section of the [book](https://doc.rust-lang.org/1.30.0/book/first-edition/generics.html#resolving-ambiguities)

**Comment by AZMCode** [comment]
Deeply appreciate it, didn't know about the turbofish.

**Comment by AZMCode** [comment]
It seems the error message changes on adding the invoke handler again, but that is a story for another day. Thank you so much.
