### ISSUE TITLE
README out of date?

### ISSUE THREAD

**Issue by Nonameghost** [Boscop/web-view#228]
Hello!

I've been exploring the examples, and I ran into an issue where I couldn't run the "Frameless" example. I got really confused at my incompetence at copy/pasting code before I realized that I simply had an out of date version of web-view.

For some reason the README says to include:

    web-view = { version = "0.5.4" }

While the latest on crates.io is **0.6.3**.

This doesn't seem intentional, I figured I'd point it out, making a PR feels like overkill.

**Comment by zxey** [comment]
Thanks for the heads up, I sometimes forget to update the version in readme. It should be fixed now.
