### ISSUE TITLE
Window Handle (hwnd)

### ISSUE THREAD

**Issue by Arvkus** [Boscop/web-view#233]
Is it possible to get window handle (hwnd)?

**Comment by zxey** [comment]
It is not, but it should not be hard to add it (we just need to add getter for it - something like native_handle()).

**Comment by Regentag** [comment]
My fork implemented it. Currently only implemented for Edge and MSHTML.
I plan to PR someday when I finish the code that supports Gtk and Cocoa.

https://github.com/Regentag/web-view

example code:
```rust
    let mut webview = web_view::builder()
        .build()
        .unwrap();
    let hwnd = webview.window_handle();
```

The `window_handle()` function returns web_view window's HWND.

**Comment by zxey** [comment]
Added in #258, closing.

**Comment by Arvkus** [comment]
Thank you.
