### ISSUE TITLE
Possible to disable frame rate limit ?

### ISSUE THREAD

**Issue by Aomitsu** [Boscop/web-view#238]
Hello
I want to create a client for a WebGL game but I'm limited to 60 fps ...
I've been looking for hours, and I don't know how to do it, is it possible ?

**Comment by FrankenApps** [comment]
Are you using a library like ThreeJS? If you are on Windows, you can try to use Chromium Edge and add the flag --disable-gpu-vsync. You would unfortunately need to modify the library yourself however. Also note that the majority of WebGL Apps is actually running at Max 60 FPS...
