### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by gdavies3** [Boscop/web-view#241]
Running even the "minimal" example on my Macbook causes the CPU utilization to max out (stays at around 99%) for the web-view process. This affects the latest master commit (`45a250223d0289b1cd66e7918b30c9d84562deee`) but not the latest release (`0.6.3`). I made sure my Rust version was updated and tried both debug and release builds but the problem continues to exist. The macOS version I am using is `10.15.7 (19H2)`. Thanks.

**Comment by jcbritobr** [comment]
I can confirm this on windows  10 x64 with rust 1.47 msvc toolchain:

![image](https://user-images.githubusercontent.com/6579862/99578774-14884f00-29bc-11eb-88d5-7dc707bf289f.png)

**Comment by gdavies3** [comment]
This is also an issue with the 0.7 release. It makes the library unusable.

**Comment by sam701** [comment]
I can confirm, I have the same issue on mac. Version `0.7.1`

**Comment by gBopHuk** [comment]
Confirm on Linux with 0.7.1 version

**Comment by helgoboss** [comment]
This is caused by commit dbc1f7e68ab83fe75e3a73c4f21a57c31b8c2a51. See #210.

**Comment by gdavies3** [comment]
This was fixed by https://github.com/Boscop/web-view/commit/abb0721829d9764d07d8df08c249de9b27cd7447.
