### ISSUE TITLE
Passing data to webview without serializing

### ISSUE THREAD

**Issue by N4tus** [Boscop/web-view#260]
Is there  a way to use data from rust in js without serializing the data first? In my case this data is just a buffer of numbers used in web gl. The other way would be accessing the web gl context from the rust side. However i also dont know how to do this.

**Comment by zxey** [comment]
There is unfortunately no way to use data from rust in js without serializing them first, they are both different languages and they need some common ground to communicate on, and that is json in this case.

Nevertheless, if you have binary data that you want processed from both sides, you can use websockets, you start websocket server on the Rust side and connect to it from JS side, you can then exchange data however you want.
