### ISSUE TITLE
Update crates.io release

### ISSUE THREAD

**Issue by jkelleyrtp** [Boscop/web-view#267]
https://github.com/Boscop/web-view/commit/abb0721829d9764d07d8df08c249de9b27cd7447

was recently added and fixes high CPU. It would be great to get a release out (0.7.3) instead of needing to rely on master.

And, thanks for all you do. We really appreciate your hard work. 🙂

**Comment by zxey** [comment]
Sure thing, released version 0.7.3, thank you for the kind words.
