### ISSUE TITLE
Updated example with YEW framework

### ISSUE THREAD

**Issue by midnightexigent** [Boscop/web-view#269]
Hello, 

I just made an [updated example](https://github.com/midnightexigent/Webview-YEW-Web-Sys-todomvc) which uses web-sys instead of stdweb for the usage of WebView with the YEW framework. 

I also used warp + tokio + mime_guess  instead of hyper for the server. The bin size is now ~7mB, it doesn't seem to be because of warp because I tried to use hyper + tokio and the bin size went down by a couple of 100kB.. could be tokio

Anyway, I thought I should share it, could be relevant to add it to the readme of the examples

**Comment by zxey** [comment]
Looks cool, feel free to send me PR adding this to examples readme if you want it showcased.
