### ISSUE TITLE
Cant access external from webview

### ISSUE THREAD

**Issue by FlawlessDeveloper** [Boscop/web-view#280]
### Error when trying to access external to callback to `invoke_handler`

There is an error saying that the object can not be found.
See screenshots:
![image](https://user-images.githubusercontent.com/37778817/114675819-f7587200-9d08-11eb-9d55-e2d174bd7ba2.png)
![image](https://user-images.githubusercontent.com/37778817/114675985-21119900-9d09-11eb-98a9-99fb4df7cacd.png)

host os:
Arch Linux

webkit2gtk version: 
2.32.0-1

rust:
rustc 1.51.0

**Comment by philwrenn** [comment]
I had a similar issue and solved it by redefining `window.external` in the head of my html source. 

```
<script>window.external={{invoke:function(x){{window.webkit.messageHandlers.external.postMessage(x);}}}};</script>
```

**Comment by martinellison** [comment]
Thanks for this. Perhaps the crate doco could be updated accordingly.

Ref erring to [my corrresponding question on Stack](https://stackoverflow.com/questions/67120536/replacement-for-window-external-invoke-in-browser-javascript).

**Comment by kellpossible** [comment]
the examples also need updating too
