### ISSUE TITLE
Attach to a parent window?

### ISSUE THREAD

**Issue by adam-hanna** [Boscop/web-view#283]
In the audio production world, developers can build VST plugins. These plugins can have GUI's but need to attach the GUI to an externally managed window.

Is it possible to add a feature to this library to allow such functionality?

For example, here's a rust crate for vst gui's that opens a web view and attaches it to a parent window:
https://github.com/vanderlokken/rust-vst-gui/blob/c71ca8df17bbfb2b109aa72ffc05bbf56e3aeadd/src/lib.rs#L56

Here's the maintaners thoughts on using this library for cross-browser support:
https://github.com/vanderlokken/rust-vst-gui/issues/8#issuecomment-832985277

EDIT
ACK! This has already been mentioned in the Readme! So Sorry!

**Comment by pythoneer** [comment]
Just to add on a usecases i have an "old" application in Qt with two QtWebViews managed by the application – its basically just a convenience for managing two browser windows for the user for managing multiple accounts etc. But maintaining and deploying this application for Linux/mac/Win is quite labor intense(Qt by itself and the Webview with openssl dependencies etc.) and i would love to replace it with something like [fltk-rs](https://github.com/fltk-rs/fltk-rs) and two embedded web-views. Would love if this could work like the embedded [VLC example](https://github.com/fltk-rs/demos/blob/master/libvlc/src/main.rs#L35-L49) as an additional inspiration.

**Comment by adam-hanna** [comment]
Also adding @mikesoylu to the thread who may be able to provide comment (he forked @vanderlokken's code to work with MacOS).

https://github.com/mikesoylu/rust-vst-gui

**Comment by pythoneer** [comment]
If i am not fully mistaken the underlying c-lib should already support that, no?

https://raw.githubusercontent.com/zserge/webview/master/webview.h

```c
// Creates a new webview instance. If debug is non-zero - developer tools will
// be enabled (if the platform supports them). Window parameter can be a
// pointer to the native window handle. If it's non-null - then child WebView
// is embedded into the given parent window. Otherwise a new window is created.
// Depending on the platform, a GtkWindow, NSWindow or HWND pointer can be
// passed here.
WEBVIEW_API webview_t webview_create(int debug, void *window);
```

i tried digging through the code a little bit with `webview_sys` and wondering why this is so different from `webview.h` different version or handmade wrapper?

**Comment by mikesoylu** [comment]
Hi was able to do it with cocoa(just for some apple specific stuff) and webview-sys. Relevant code can be found here in the fork: https://github.com/mikesoylu/rust-vst-gui/pull/1/commits/3b56730f190e1907b60a2f41d4c9a968f228fcad#diff-7ea3d8f419ddb71f86b7e524c1c7025cf92f1b46ad6457e505795209408f67f1

**Comment by lucianoiam** [comment]
I've done this but for a C++ plugins framework [here](https://github.com/lucianoiam/hiphop). I don't know Rust but it should be possible to extract the webview classes and write a wrapper. The classes were written from scratch with all the plugin specifics in mind: no statics, no link to GUI toolkits, etc.

This [reverb plugin](https://github.com/lucianoiam/castello) has a webview based UI.

**Comment by SkyLeite** [comment]
Hi! Any updates on this? It would be extremely helpful for writing UI in games :)
