### ISSUE TITLE
Opening a dialog fails on Windows 10

### ISSUE THREAD

**Issue by bytebuddha** [Boscop/web-view#29]
Hey great library!. I've been using it for a personal project for a few months and as i try to port my app to windows 10 i noticed this.

Offending code is called after parsing the json recieved from window.external.invoke
```rust
let file_name = view.dialog(Dialog::SaveFile, "Choose Database File", "");
```
And in another spot
```rust
let file_name = view.dialog(Dialog::OpenFile, "Choose Database File", "");
```

Both react the same way, i never see the file dialog and it immediately returns an
empty string. Any ideas what might cause this?

**Comment by Boscop** [comment]
Not sure, I only have Win 8.1.
Do you have a minimal test example that exhibits the same behavior?
Maybe someone who also has Win 10 can test this..

**Comment by bytebuddha** [comment]
Of coarse here is a test program showing the bug 
```rust 
extern crate web_view;


use web_view::WebView;
use web_view::MyUnique;
use web_view::Content;
use web_view::Dialog;
use web_view::Alert;
use web_view::run;

const HTML: &str = r#"
<DOCTYPE html>
<html>
  <body>
      <button onclick="window.external.invoke('open')">Open File Dialog</button>
      <button onclick="window.external.invoke('save')">Save File Dialog</button>
      <button onclick="window.external.invoke('directory')">Choose Directory Dialog</button>
      <button onclick="window.external.invoke('alert-info')">Info Alert</button>
      <button onclick="window.external.invoke('alert-warning')">Warning Alert</button>
      <button onclick="window.external.invoke('alert-error')">Error Alert</button>
  </body>
</html>
"#;

fn callback(view: &mut WebView<()>, arg: &str, user_data: &mut ()) {
    match arg {
        "open" => {
            println!("Attempting to open 'OpenFile' dialog");
            view.dialog(Dialog::OpenFile, "Test Open Dialog", "");
        },
        "save" => {
            println!("Attempting to open 'SaveFile' dialog");
            view.dialog(Dialog::SaveFile, "Test Open Dialog", "");
        },
        "directory" => {
            println!("Attempting to open 'ChooseDirectory' dialog");
            view.dialog(Dialog::ChooseDirectory, "Choose Directory Dialog", "");
        },
        "alert-info" => {
            println!("Attempting to open info alert");
            view.dialog(Dialog::Alert(Alert::Info), "Info Alert", "");
        },
        "alert-warning" => {
            println!("Attempting to open warning alert");
            view.dialog(Dialog::Alert(Alert::Warning), "Info Alert", "");
        },
        "alert-error" => {
            println!("Attempting to open error alert");
            view.dialog(Dialog::Alert(Alert::Error), "Info Alert", "");
        }
        _ => {}
    }
}

fn main() {
    let (_, _) = run("open dialog test",
            Content::Html(HTML),
            Some((500, 500)),
            true,
            true,
            |_|{},
            callback,
            ()
        );

}
```

All of the alerts work so ignore those, but none of the file dialog's ever open

**Comment by zxey** [comment]
This is the strangest thing, in order to debug this, I tried to put some debug prints into original c webview source code. With the printf statements in, everything works, when I comment them out, it does not work.

**Comment by bytebuddha** [comment]
@zxey I got fed up with Windows and installed Ubuntu at work so i no longer have the means to work on this.

After reading that I think it has something to do with building webview in the build script of the webview-sys crate. Maybe something isn't getting linked correctly? I am very new to C so maybe that's a stupid question. But if there is anything i can do to help debug let me know!

**Comment by zxey** [comment]
I found that that it does not work for me when i build webview in debug mode, but it works when i build it with release mode.

**Comment by zxey** [comment]
Seems like it is uninitialized variable in webview in c code.

**Comment by zxey** [comment]
Created PR in original webview library. Should be fixed when zserge/webview#214 gets merged upstream. We can then update our submodule and get the fix.

**Comment by slier81** [comment]
Is the PR being merged already?

**Comment by prixt** [comment]
This also happens to me on Window 10, but only on the stable-msvc toolchain. Dialog functions normally when built on the stable-gnu toolchain.
