### ISSUE TITLE
Navigation between pages in my app

### ISSUE THREAD

**Issue by Randall-Coding** [Boscop/web-view#297]
Is there an example that shows navigation between pages?  

If I click on a button on the UI I want to load new html into my web-view container.  How can that be achieved?  And am I even thinking about this in the right way?

**Comment by gpietz** [comment]
Hi, 
I'm also trying to do that. Have you found a solution for it? I know there is the set_html method in the invoke handler but it's not working as expected/described. Instead of showing the new html contents, it's firing a request in the bing search engine?!

**Comment by Randall-Coding** [comment]
Ok I found the set_html() function.
