### ISSUE TITLE
Is multitouch supported?

### ISSUE THREAD

**Issue by bitdivine** [Boscop/web-view#309]
Dear all,

This looks cool but: Does this webview support multitouch?

I made a small test: I made a hello world web view with the debugger enabled, added this to the console:
```
document.querySelector('body').addEventListener('mousemove', console.log);
```
Moving one finger over the webview, I get printouts, with two I don't.  I just get crosshairs appearing for the duration of the two finger swipe, and the crosshairs don't move.  But I don't know whether that is because webview does not suport multitouch or because of some configuration issue.

A search for multitouch in the repo shows nothing, but a different term might be used.  (E.g. maybe there is a max pointers configuration??)

Best wishes, Max

**Comment by zxey** [comment]
Hello, you need to use touch events, instead of mouse events, you can see them documented [here](https://developer.mozilla.org/en-US/docs/Web/API/Touch_events/Multi-touch_interaction).
