### ISSUE TITLE
Feature Request: Support for WASM in Web-View

### ISSUE THREAD

**Issue by kerberosmansour** [Boscop/web-view#33]
I would like to use Rust as on the front in as well can Webview also support WASM so I can do that please?

**Comment by Boscop** [comment]
web-view uses IE11's engine which doesn't support wasm unfortunately.
You can use the tether crate which uses Edge's engine, but then your app won't work if Edge isn't installed (e.g. I'm running windows 8.1 and don't have Edge installed).. 
Or you could unify the web-view and tether crates into one API, then include a version of your frontend that's compiled to asm.js (either directly or from wasm) as a fallback when only IE is installed...

**Comment by rumanbsl** [comment]
This seems like a fascinating idea. I only have experience in web development. If I want to work on it, what kinds of experience should I have. Any documentation, tutorial would be much appreciated

**Comment by Boscop** [comment]
@kerberosmansour 
I did a test of compiling my Yew wasm frontend with wasm2js: 
https://github.com/WebAssembly/binaryen/issues/1781

@rumanbsl You could start by running the [Yew](https://github.com/DenisKolodin/yew) examples and understanding them, modifying them etc.

**Comment by zxey** [comment]
You can now use WASM on Windows with `edge` feature, works only on Windows 10 though.

**Comment by zxey** [comment]
Closing, WASM is supported, can be seen in yew example. Works for all backends except IE11, but you can use Edge on Windows 10, nothing much we can do for IE11 (except maybe using wasm2js as Boscop suggested).
