### ISSUE TITLE
web-view 0.1.2 dependency fails Travis builds

### ISSUE THREAD

**Issue by WrinklyNinja** [Boscop/web-view#4]
Thanks for this library, it's proving very useful to me. Unfortunately, the latest release fails to build on Travis. Looking through your commit history, it looks like you fixed this after you published the latest release?

I could just depend on an unpublished commit, but I've got three requests that would generally make usage of your library much easier, please could you:

1. Release a new version that builds on Travis.
2. Tag your release commits (and push the tags to GitHub) so it's easy to see what got released when. AFAIK there's no way to map between commits and versions published on crates.io, which makes it difficult to tell what changes are included in what release.
3. Indicate what version of zserge/webview you're using? It looks like you've included the C header from zserge/webview in this repo, but I can't find anything that says what revision you got that header from. Again, it makes keeping track of changes pretty difficult, and it looks like the upstream repo is pretty active. 

   When I pull external code into my repos, one of the things I do is include the hash of the commit in the upstream repo I got the code from in my commit message, something like that would be great.

Thanks!

**Comment by Boscop** [comment]
Thanks!
1. Yes, I want to get it to build on travis asap, but I don't know what's wrong, maybe you have an idea?
The previous discussion was here: https://github.com/Boscop/web-view/pull/1#issuecomment-359609154
It builds on stable, and macos stable, but fails on nightly and beta, any idea how to fix it? :)

2. Good idea. Do I just have to do `git tag -a v1 -m "vX.Y.Z"` and then `git push --tags` before `cargo publish`?

3. Yes, I'll add the hash to the Readme (I think it makes more sense than in every commit message because it doesn't change with every commit.) Currently it uses [5a16d33](https://github.com/zserge/webview/tree/5a16d3335bbc2178e3f3adae3e17f1cd06bf71aa).

**Comment by WrinklyNinja** [comment]
1. Well, it looks like the failing Linux builds are missing the build matrix config (you can see in the "View config" tab in each build job), so it looks like the Travis config needs adjustment. Also, for nightly I've generally seen Travis configs allow failures on nightly because it's prone to breakage, and you probably don't want it failing your builds.
2. Even just a `git tag X.Y.Z`, `git push --tags` would be good enough, before or after the cargo publish (I do mine after just in case publish fails for whatever reason). I'm not fussed about annotated vs non-annotated tags.
3. Well, I actually meant only in the commits in which you change the file, e.g. in 450b215 the commit message could have been something like:

   > Add webview.h
   >
   > From zserge/webview#5a16d33.

   Then whenever you update that file the message would be a similar "Update webview.h ... zserge/webview#whatever". That way `git log webview-c/webview.h` gives you a history of revisions used, and IMO it's easier to remember to stick the hash in the commit message than it is to remember to update the readme.

**Comment by Boscop** [comment]
Thanks.
1. How would you suggest changing the [.travis.yml file](https://github.com/Boscop/web-view/blob/master/.travis.yml) to use the same matrix config for all, and to allow failure on nightly?
2. Ok, I'll do that. I thought only tags with `-a` will be pushed..
3. Ah yes, that sounds like a good solution.

**Comment by WrinklyNinja** [comment]
Any chance of a new release now that Travis is passing?

**Comment by Boscop** [comment]
Sorry, I was a little busy.. :)
I published a new version now (0.1.3), but now it doesn't show the latest 2 commits on master, only on the tag, why?
https://github.com/Boscop/web-view/commits/0.1.3
vs:
https://github.com/Boscop/web-view/commits/master
I added the tag after committing both commits to master.

**Comment by WrinklyNinja** [comment]
Thanks! Try `git push` on master (or `git push origin master:master`) too. `git push --tags` doesn't push the branch you're on, only the tags themselves and the commits in their history.

**Comment by Boscop** [comment]
Ah thanks, I just realized it.. :)
Is everything ok now?

**Comment by WrinklyNinja** [comment]
Yes, everything works now. 👍
