### ISSUE TITLE
Unicode support for windows.

### ISSUE THREAD

**Issue by zoumi** [Boscop/web-view#41]
On windows platform, the title with noascii chars can not be shown correctly.
The string should be OsStr not Cstr.

**Comment by qlobafftar** [comment]
Workaround:
`let ttl: Vec<u8> = vec![...array_of_raw_bytes_in_singlebyte_encoding...];  // window created with Ascii version of WinApi function
web_view::builder()
  .title(unsafe {std::str::from_utf8_unchecked(&ttl)})
   .content(Content::Url("http://localhost:8000"))
   .size(800, 600)
   .resizable(true)
   .debug(false)
   .user_data(())
   .invoke_handler(|_webview, _arg| Ok(()))
   .run()
   .unwrap();`

**Comment by zoumi** [comment]
Thanks!
