### ISSUE TITLE
Chromep. Use an embedded chrome on all desktops

### ISSUE THREAD

**Issue by gedw99** [Boscop/web-view#47]
This is just an idea but it seems to solve a ton of issues.

Basically there is a new golang project that allows you to embed chrome into your app for every desktop. So you get the same browser and you control it's update.
Zserge/Lorca is its name.

Now rust has compelling wasm story. So why not try to use the Lorca approach. It's really just using the chrome tooling API to do its magic and when you look at the Lorca code you can see how simple it would be to support rust.

You can do almost everything you can do with fat electron.
The one thing I have not worked out is how to have an app icon when it opens. It shows the Google Chrome icon.

This would be an awesome setup to use with yew. I have been playing with yew and am amazed how easy and well done it is.

Btw if anyone knows a yew project using the material design components please holler :)

**Comment by zxey** [comment]
This is definitely a cool idea, but I think it is out of scope for this project. This project is only a wrapper for [this](https://github.com/zserge/webview) library.
