### ISSUE TITLE
Can't run on Ubuntu 18

### ISSUE THREAD

**Issue by Paulo-Jorge-PM** [Boscop/web-view#62]
Hi. Thank you for your work. I would like to try this library but it is not running in Ubuntu 18:

I just added this import to the main.rs of a running app of mine:
extern crate web_view;
use web_view::*;

And added this to the "Cargo.toml":
web-view = "0.4.1"

The rest is a running app of mine, just wanted to test webview and build from there.

But when I run "cargo build" to test it, it gives this error:

"Compiling webview-sys v0.1.2
error: failed to run custom build command for `webview-sys v0.1.2`
process didn't exit successfully: `/home/paulo/Repos/rust/target/debug/build/webview-sys-960829160a197e3d/build-script-build` (exit code: 101)
--- stderr
fatal: not a git repository (or any of the parent directories): .git
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failure { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"webkit2gtk-4.0\" \"webkit2gtk-4.0 >= 2.8\"", output: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "Package webkit2gtk-4.0 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `webkit2gtk-4.0.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'webkit2gtk-4.0\' found\nPackage webkit2gtk-4.0 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `webkit2gtk-4.0.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'webkit2gtk-4.0\' found\n" } }', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace."

Is it related to be running in Ubuntu 18? Was it tested only in windows?

**Comment by zxey** [comment]
You are missing libwebkit2gtk library, try installing it with `sudo apt install libwebkit2gtk-4.0-dev` and see if it helps.

**Comment by Paulo-Jorge-PM** [comment]
Thank you for your time, solved :)
