### ISSUE TITLE
web-view sample using Yew

### ISSUE THREAD

**Issue by jimmy-smile** [Boscop/web-view#66]
Hello..trying to find sample on using yew framework and wrap it with web-view.  Any sample please.

Thanks in advance.

**Comment by Boscop** [comment]
IE11 doesn't support Wasm. But you can compile wasm to js with binaryen. 
https://github.com/Boscop/web-view/issues/33

**Comment by Boscop** [comment]
I know it's unsatisfactory, I hope that we can also support WASM in web-view somehow, but IE cannot do it..
If you want your app to run on Win 8 with web-view, it has to use IE's engine and so it must be compiled to js (at least the version of your app for Win 8).

**Comment by zxey** [comment]
There is now todo-yew in examples, thanks to #91.
