### ISSUE TITLE
EdgeHTML Support

### ISSUE THREAD

**Issue by khionu** [Boscop/web-view#67]
> As for MSHTML vs EdgeHTML, I would like to keep MSHTML for as long as possible and create EdgeHTML alongside that which can be enabled with feature flag. The reason is that Rust supports Windows 7 and newer (AFAIK) and EdgeHTML supports Windows 10 only.

> _Originally posted by @zxey in https://github.com/Boscop/web-view/issues/64#issuecomment-529650348_

While Rust does [only have Tier 1 support Win7+](https://forge.rust-lang.org/release/platform-support.html), post-MSHTML support is a necessity for WASM. As noted by this repo's issue tracker, WASM support is highly desired.

**Comment by zxey** [comment]
I agree, WASM support is desired, there are couple of ways we can achieve this:
- take EdgeHTML implementation from zserge/webview (webview-x) branch [here](https://github.com/zserge/webview/tree/webview-x)
- implement it directly here in Rust

This is also important so we can use frameworks that compile to WASM by default such as Yew (see also issue #66).

**Comment by Boscop** [comment]
Yes, Wasm support would be great to have. But also on Windows 8.1 (which I'm using btw). 
EdgeHTML is not available on Win 8.
I saw on reddit, someone was working on porting CEF to Rust, not sure what the status is, does anyone have more info on that?

**Comment by nothingismagick** [comment]
Last I heard CEF on rust is dead. Might be wrong though. We won't be using
it at tauri though because of chromium deps and how that breaks FLOSS.
We're already looking into options for a post webview future though...

**Comment by zxey** [comment]
Implemented under the `edge` feature.
