### ISSUE TITLE
Allow not terminating the app on WebView drop

### ISSUE THREAD

**Issue by ivanmoskalev** [Boscop/web-view#72]
Currently dropping the instance of `WebView` causes app termination (at least, on macOS). 

Though convenient for simple cases, this isn't flexible enough for applications where the main window is not expected to be present at all time (such as menubar applications on macOS or tray apps on Windows).

Proposed solution: add a property that would allow to skip the termination when the window is dropped.

I can introduce the necessary changes and publish a PR, if the proposal is accepted.

**Comment by zxey** [comment]
Sure, go ahead, just make sure it does not leak any resources if the window does not get dropped. And if you can please test it at least a bit on Windows and Linux.

**Comment by FreeMasen** [comment]
Does the merge of #107 solve this issue as well?

**Comment by ivanmoskalev** [comment]
@FreeMasen Yes! Thank you. I'm sorry I have been unresponsive – I had to choose Sciter for my app's UI in the end and had no time to follow through with this issue.
