### ISSUE TITLE
Edge feature on Windows 10 results in linker-error

### ISSUE THREAD

**Issue by kastenbutt** [Boscop/web-view#89]
I tried to run the basic todo example with the edge feature enabled:

```toml
webview-sys = { path = "webview-sys", version = "0.3.1", features=["edge"] }
```

```
cargo run --example todo
```

This resulted in a linker error:

> error LNK2019: Unresolved external symbol \"__imp_CoCreateInstance\" in function \"webview_dialog\".\r\nlibwebview_sys-573306a327093e04.rlib(webview_edge.o) : error LNK2019: Unresolved external symbol \"__imp_CoWaitForMultipleHandles\" in function \"\"public: __cdecl webview::webview::webview(void (__cdecl*)(void *,char const *),char const *,int,int,bool,bool)\" (??0webview@0@QEAA@P6AXPEAXPEBD@Z1HH_N3@Z)\".\r\n

The symbols are from Ole32.lib and I figured webview-sys should link against that. I had a look at webview-sys's build.rs and noticed that Ole32 is in fact not linked against if the edge feature is set. Adding `println!("cargo:rustc-link-lib=ole32");` solved my linker issue.

Has anyone else had this issue? If so, I propose to change `webview-sys/build.rs` accordingly. If not, I wonder why this linker-error occurs.

Some info:

- cargo 1.39.0 (1c6ec66d5 2019-09-30)
- rustup 1.20.2 (13979c968 2019-10-16)
- Default host: x86_64-pc-windows-msvc
- Default Toolchain: stable-x86_64-pc-windows-msvc
- VC++ 2017 version 15.9 v14.6 latest v141 tools
- Windows 10 SDK 10.0.17763.0

**Comment by zxey** [comment]
Hi, could you check if #90 fixes your error? I added the ole32 library.

**Comment by kastenbutt** [comment]
It does! Thanks :)
