### ISSUE TITLE
Apply clippy suggestions

### ISSUE THREAD

**Issue by pzmarzly** [Boscop/web-view#9]
`cargo clippy` results in several improvements to this lib. We can categorise them in 3 categories:

- unnecessary code (f.e. explicit lifetimes) - easy to fix, just follow the suggestions
- `#[inline(always)]` - it shouldn't be used for performance tuning (`lto` in `Cargo.toml` does better job), but sometimes it is required for other reasons
- `run()` taking too many arguments - I agree that a struct may be a better choice (as parameters are named and Rust compiler enforces using all fields, but whether to change API or not is a package dev's choice

**Comment by Boscop** [comment]
Thanks, I will look into it..
I will add a Builder struct instead of that one big `run()` function..
