### ISSUE TITLE
webview_inject_css only available for Edge target

### ISSUE THREAD

**Issue by atwupack** [Boscop/web-view#93]
The implementation of webview_inject_css is only in webview_edge.cpp but it should work on all targets if I understand the original webview.h correctly. If I compile an application using the MSHTML target using inject_css, the linker complains about the missing implementation.
I think it should be moved to the webview.h to be available everywhere. I can fix that and create a PR for it. Do you need it only on master or on the other branches also?

**Comment by zxey** [comment]
Hello, this should definitely be in all other backends. If you could create a PR that would we wonderfull, only `master` is fine.
