### ISSUE TITLE
Windows 10 blurry interface

### ISSUE THREAD

**Issue by GioPat** [Boscop/web-view#99]
Hello!
After trying the timer example, I realized that the interface is blurry. 
This is a screen shot:
![wv_blurry](https://user-images.githubusercontent.com/9217515/70388990-e03d9d80-19b9-11ea-93d3-5298c1e0c1fa.png)

These are my system specification:
![image](https://user-images.githubusercontent.com/9217515/70378697-b89bf600-1923-11ea-9d8f-cabc66fbe33a.png)

And these are my screen settings:
![image](https://user-images.githubusercontent.com/9217515/70388997-f3e90400-19b9-11ea-8ff7-4098b597d913.png)

Thank you!

**Comment by parkovski** [comment]
This is due to not enabling HiDPI support through the Windows APIs. Basically, two things need to be done. First, turn on DPI support in app startup (there's a new function and a fallback function), looks something like this:

```c++
bool enableDpiAwareness() {
  auto libUser32 = GetModuleHandleW(L"user32.dll");
  if (libUser32) {
    auto fnSetThreadDpiAwarenessContext =
      reinterpret_cast<decltype(&SetThreadDpiAwarenessContext)>(
        GetProcAddress(libUser32, "SetThreadDpiAwarenessContext")
      );
    if (fnSetThreadDpiAwarenessContext
        && fnSetThreadDpiAwarenessContext(DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2)) {
      return true;
    }
  }

  auto libShcore = LoadLibraryW(L"shcore.dll");
  if (!libShcore) {
    return false;
  }
  auto fnSetProcessDpiAwareness =
    reinterpret_cast<HRESULT (WINAPI *)(int)>(
      GetProcAddress(libShcore, "SetProcessDpiAwareness");
    );
  if (!fnSetProcessDpiAwareness || !fnSetProcessDpiAwareness(2 /* PROCESS_PER_MONITOR_DPI_AWARE */)) {
    FreeLibrary(libShcore);
    return false;
  }
  FreeLibrary(libShcore);
  return true;
}
```

Then you need to handle DPI changes which can happen on a settings change, but also just by dragging the app in multi-monitor setups. This code goes in your window handler:

```c++
// ...
case WM_DPICHANGED:
  {
    // Resize the window to Windows' recommended new rectangle.
    auto rect = reinterpret_cast<LPRECT>(lParam);
    auto x = rect->left;
    auto y = rect->top;
    auto w = rect->right - x;
    auto h = rect->bottom - y;
    SetWindowPos(hWnd, nullptr, x, y, w, h, SWP_NOZORDER);

    // If you need scale and resolution info, include this:
    auto monitor = MonitorFromWindow(hWnd, MONITOR_DEFAULTTONEAREST);
    MONITORINFOEXW mi{};
    mi.cbSize = sizeof(MONITORINFOEXW);
    GetMonitorInfoW(monitor, &mi);
    auto scale = LOWORD(wParam) / (float)USER_DEFAULT_SCREEN_DPI;
    auto xres = mi.rcMonitor.right - mi.rcMonitor.left;
    auto yres = mi.rcMonitor.bottom - mi.rcMonitor.top;
  }
  break;
// ...
```

If I find the time I'll make these changes & send a PR, otherwise hopefully this saves someone a bit of research.

**Comment by GioPat** [comment]
Hello, thanks for the quick reply.

These modifications should be included in this [source file](https://github.com/Boscop/web-view/blob/master/webview-sys/webview_mshtml.c)? 
If so I could try to create a PR (Don't have experience with web-view but still I can try).

Thank you

**Comment by ffactory-ofcl** [comment]
Bump. I just discovered this repo as well as [huytd/webview ](https://github.com/huytd/webview). Interesting that this was opened just two days ago.
Got it to work, but blurryness out of the box is kind of a bummer.

**Comment by parkovski** [comment]
@GioPat They'd need to go in that one and `webview_edge.cpp`. First part should be before the first window is created.

**Comment by GioPat** [comment]
@parkovski Will try to create a PR with the info that I have! :) 

Thanks

**Comment by sopium** [comment]
For `mshtml`, you need to make the browser DPI aware too, or CSS pixels won't scale.

In `UI_GetHostInfo`:
```
  pInfo->dwFlags = DOCHOSTUIFLAG_NO3DBORDER | DOCHOSTUIFLAG_DPI_AWARE;
```

**Comment by GioPat** [comment]
You can find on my [fork](https://github.com/GioPat/web-view/tree/feature/enable-dpi-awareness) the commits with the proposed changes.

Command `cargo build` is building fine but I have still the issue. Is there anything that I'm missing?

P.S. If you try to go in _Right click on the exe -> Properties -> Compatibility -> Change High DPI Settings -> Override high DPI scaling behavior -> Select Application_: it's fixing the issue also using master branch.

**Comment by parkovski** [comment]
I'll try to look more in depth later but a couple things I noticed:
[These two typedefs](https://github.com/GioPat/web-view/blob/9595e29ef73a21cc8127a2033895826791d94ba6/webview-sys/webview_mshtml.c#L113) need the `WINAPI` modifier, it's important for 32 bit apps.
Please try compiling the Edge file, I saw a naming issue.

**Comment by GioPat** [comment]
> I'll try to look more in depth later but a couple things I noticed:
> [These two typedefs](https://github.com/GioPat/web-view/blob/9595e29ef73a21cc8127a2033895826791d94ba6/webview-sys/webview_mshtml.c#L113) need the `WINAPI` modifier, it's important for 32 bit apps.
> Please try compiling the Edge file, I saw a naming issue.

Thanks, I ran cargo build in the root of the project, what's the procedure for compiling the Edge file?

**Comment by GioPat** [comment]
Thanks to your comments @parkovski, @sopium the code is working fine 💪 .

> Please try compiling the Edge file, I saw a naming issue.

Fixed, it's compiling fine :)

I will open a PR and connect to this issue.
